project: linear_quantized_gaze
run_name: linear_quantized_gaze

ckpt_dir: ./training/gaze_estimation/ckpts_linear_quantized
dataset_dir: ./training/gaze_estimation/utils/mpii_preprocess/annotations.txt

batch_size: 128
num_workers: 8
epoch: 200
criterion: MSELoss

optimizer: Adam
optimizer_parameters:
  lr: 0.001

model: MyModelv7
arch: proxyless-w0.3-r176_imagenet
logger: wandb
