project: gaze_mpiigaze
run_name: gaze_mpiigaze

ckpt_dir: ./ckpts_kmeans
dataset_dir: ./utils/mpii_preprocess/annotations.txt

batch_size: 128
num_workers: 8
epoch: 200
criterion: MSELoss

optimizer: Adam
optimizer_parameters:
  lr: 0.0005

model: MyModelv7
arch: proxyless-w0.3-r176_imagenet
logger: wandb

